all:
  children:
    production:
      hosts:
        adsecure-server:
          ansible_host: localhost
          ansible_connection: local
          ansible_user: debsae502
      vars:
        env_type: production
